-- MAXSIZE SETADO PARA 11GB DEVIDO A RESTRIÇÃO DE ARMAZENAMENTO DA VERSÃO XE

CREATE TABLESPACE sankhya
DATAFILE 'sankhya.dbf' SIZE 100M REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 11000M
ONLINE;

CREATE TABLESPACE sankind
DATAFILE 'sankind.dbf' SIZE 100M REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 11000M
ONLINE;

CREATE TABLESPACE sanklob
DATAFILE 'sanklob.dbf' SIZE 100M REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 11000M
ONLINE;



-- PASSANDO CAMINHO COMPLETO DO NOVO ARQUIVO

CREATE TABLESPACE sankhya
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/sankhya.dbf' SIZE 100M REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 11000M
ONLINE;

CREATE TABLESPACE sankind
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/sankind.dbf' SIZE 100M REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 11000M
ONLINE;

CREATE TABLESPACE sanklob
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/sanklob.dbf' SIZE 100M REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 11000M
ONLINE;
