CREATE USER TESTE IDENTIFIED BY g5x2urim DEFAULT TABLESPACE SANKHYA TEMPORARY TABLESPACE TEMP;
/
GRANT RESOURCE, CONNECT TO TESTE
/
ALTER USER TESTE QUOTA UNLIMITED ON SANKHYA
/
ALTER USER TESTE QUOTA UNLIMITED ON SANKIND
/
GRANT SELECT ON V_$SESSION TO TESTE
/
GRANT SELECT ON DBA_TABLES TO TESTE
/
GRANT CREATE SESSION TO TESTE
/
GRANT SELECT ON DBA_TAB_COLUMNS TO TESTE
/
GRANT SELECT ON DBA_CONSTRAINTS TO TESTE
/
GRANT SELECT ON DBA_TRIGGERS TO TESTE
/
GRANT SELECT ON DBA_INDEXES TO TESTE
/
GRANT SELECT ON DBA_VIEWS TO TESTE
/
GRANT SELECT ON DBA_IND_COLUMNS TO TESTE
/
GRANT SELECT ON DBA_OBJECTS TO TESTE
/
GRANT EXP_FULL_DATABASE TO TESTE
/
GRANT IMP_FULL_DATABASE TO TESTE
/
GRANT CREATE ANY DIRECTORY TO TESTE
/
GRANT SELECT ON DBA_PROCEDURES TO TESTE
/
GRANT CREATE ANY VIEW TO TESTE
/
GRANT CREATE ANY JOB TO TESTE
/
GRANT SELECT ON SCHEDULER$_JOB TO TESTE
/
GRANT CREATE JOB TO TESTE
/
GRANT EXECUTE ON UTL_FILE TO TESTE
/
GRANT EXECUTE ON DBMS_CRYPTO TO TESTE
/
GRANT EXECUTE ON UTL_SMTP TO TESTE
/
GRANT EXECUTE ON UTL_TCP TO TESTE
/
GRANT EXECUTE ON UTL_HTTP TO TESTE
/
GRANT EXECUTE ON DBMS_ALERT TO TESTE
/
GRANT CREATE MATERIALIZED VIEW TO TESTE;
