-- COMANDOS USADOS COM O USUÁRIO SYSTEM -- ORACLE 11G

CREATE TABLESPACE minhatbs
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\minhatbs.dbf' SIZE 100M REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 500M
ONLINE;

CREATE USER deive IDENTIFIED BY "123"
DEFAULT TABLESPACE minhatbs
TEMPORARY TABLESPACE temp;

GRANT
CREATE CLUSTER,
CREATE DATABASE LINK,
CREATE PROCEDURE,
CREATE SESSION,
CREATE SEQUENCE,
CREATE SYNONYM,
CREATE TABLE,
CREATE ANY TYPE,
CREATE TRIGGER,
CREATE VIEW
TO deive;

GRANT ALTER SESSION TO deive;
GRANT UNLIMITED TABLESPACE TO deive;